title: Iwan Fals
description: Iwan Fals yang bernama lahir Virgiawan Listanto adalah seorang Penyanyi beraliran Balada, Pop, Rock, dan Country yang menjadi salah satu legenda di Indonesia. Wikipedia
genre: [Balada, Pop, Rock, Country]

